### PR TITLE
Added handling of (defs starting with) "default"

### PR DESCRIPTION
**Pull request by tomdl89**
Before, the keyword control pattern match would match all words starting with "def" (if surrounded by certain characters).
After, the match behaves the same, except it will not match words starting with "default" (including "defaults" "defaulting" etc.). "Default" and its derivatives are considered the only words staring with "def" that would be commonly used in code which are nearly always not definitions.

### CODE REVIEW

**Comment by PEZ** [comment]
I'd love this change. In fact I have sometimes even avoided naming stuff with the prefix `default`, because it looks crazy when highlighted as it is today.

However, as we have discussed offline, this change needs to originate here: https://github.com/BetterThanTomorrow/calva-fmt/tree/develop/atom-language-clojure

(Just keep pushing changes to your `def-ault-handling` branch and the PR will be updated, in case you didn't know that.)

**Comment by tomdl89** [comment]
I have put the changes in the cson and coffee files instead. I assume this gets converted to json when built.

**Comment by PEZ** [comment]
Thanks! I'll have a look.

**Comment by PEZ** [comment]
Awesome. Many thanks for this!

**Pull request merged**
